<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\iconfont.ttf" />
    <None Remove="Fonts\Orbitron-Medium.ttf" />
    <None Remove="Resources\Arrow.jpg" />
    <None Remove="Resources\char_state_tab.json" />
    <None Remove="Resources\cn_synonym.txt" />
    <None Remove="Resources\dict.txt" />
    <None Remove="Resources\idf.txt" />
    <None Remove="Resources\Licence.jpg" />
    <None Remove="Resources\LoginLeft.jpg" />
    <None Remove="Resources\Logo.jpg" />
    <None Remove="Resources\pos_prob_emit.json" />
    <None Remove="Resources\pos_prob_start.json" />
    <None Remove="Resources\pos_prob_trans.json" />
    <None Remove="Resources\prob_emit.json" />
    <None Remove="Resources\prob_trans.json" />
    <None Remove="Resources\StartBackground.jpg" />
    <None Remove="Resources\stopwords.txt" />
    <None Remove="Resources\SubSuccess.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
    <PackageReference Include="O2S.Components.PDFView4NET.WPF" Version="11.3.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BLL\BLL.csproj" />
    <ProjectReference Include="..\ChartRender\ChartRender.csproj" />
    <ProjectReference Include="..\CsharpAPI\CsharpAPI.csproj" />
    <ProjectReference Include="..\FileRender\FileRender.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\iconfont.ttf" />
    <Resource Include="Fonts\Orbitron-Medium.ttf" />
    <Resource Include="Resources\Arrow.jpg" />
    <Resource Include="Resources\char_state_tab.json" />
    <Resource Include="Resources\cn_synonym.txt" />
    <Resource Include="Resources\dict.txt" />
    <Resource Include="Resources\idf.txt" />
    <Resource Include="Resources\Licence.jpg" />
    <Resource Include="Resources\LoginLeft.jpg" />
    <Resource Include="Resources\Logo.jpg" />
    <Resource Include="Resources\pos_prob_emit.json" />
    <Resource Include="Resources\pos_prob_start.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\pos_prob_trans.json" />
    <Resource Include="Resources\prob_emit.json" />
    <Resource Include="Resources\prob_trans.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\StartBackground.jpg" />
    <Resource Include="Resources\stopwords.txt" />
    <Resource Include="Resources\SubSuccess.jpg" />
  </ItemGroup>

</Project>
