<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="O2S.Components.PDFView4NET.WPF" Version="11.3.13" />
    <PackageReference Include="PdfiumViewer" Version="2.13.0" />
  </ItemGroup>

</Project>
